// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHiMBq5GQJKpSCP49Eqvg8Rs69o4BntaE',
    appId: '1:243663739777:web:81180c4b537e738bafe680',
    messagingSenderId: '243663739777',
    projectId: 'chatbot-edeef',
    authDomain: 'chatbot-edeef.firebaseapp.com',
    storageBucket: 'chatbot-edeef.appspot.com',
    measurementId: 'G-7VTGC47M4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Mh45AHPWVou8PkxdQHwa_6o4opha1K0',
    appId: '1:243663739777:android:18d2ee043584b675afe680',
    messagingSenderId: '243663739777',
    projectId: 'chatbot-edeef',
    storageBucket: 'chatbot-edeef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Kg1H2FApUCsPrIc_ba2lCzVk1E4SZOM',
    appId: '1:243663739777:ios:05e6b53379c7ecf7afe680',
    messagingSenderId: '243663739777',
    projectId: 'chatbot-edeef',
    storageBucket: 'chatbot-edeef.appspot.com',
    iosBundleId: 'com.example.gemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Kg1H2FApUCsPrIc_ba2lCzVk1E4SZOM',
    appId: '1:243663739777:ios:05e6b53379c7ecf7afe680',
    messagingSenderId: '243663739777',
    projectId: 'chatbot-edeef',
    storageBucket: 'chatbot-edeef.appspot.com',
    iosBundleId: 'com.example.gemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHiMBq5GQJKpSCP49Eqvg8Rs69o4BntaE',
    appId: '1:243663739777:web:f7ecb37e55e1ebacafe680',
    messagingSenderId: '243663739777',
    projectId: 'chatbot-edeef',
    authDomain: 'chatbot-edeef.firebaseapp.com',
    storageBucket: 'chatbot-edeef.appspot.com',
    measurementId: 'G-FZBLYDZRRN',
  );
}
